#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-utils
Version  : 1
Release  : 13
URL      : https://cgit.freedesktop.org/xdg/xdg-utils/snapshot/0d6eebb27c562e8644ccf616ebdbddf82d0d2dd8.tar.gz
Source0  : https://cgit.freedesktop.org/xdg/xdg-utils/snapshot/0d6eebb27c562e8644ccf616ebdbddf82d0d2dd8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xdg-utils-bin
Requires: xdg-utils-doc
BuildRequires : docbook-xml
BuildRequires : libxml2
BuildRequires : libxslt
BuildRequires : libxslt-bin
BuildRequires : links
BuildRequires : util-linux
BuildRequires : xmlto

%description
xdg-utils
---------
The xdg-utils package is a set of simple scripts that provide
basic desktop integration functions for any Free Desktop, such as Linux.

%package bin
Summary: bin components for the xdg-utils package.
Group: Binaries

%description bin
bin components for the xdg-utils package.


%package doc
Summary: doc components for the xdg-utils package.
Group: Documentation

%description doc
doc components for the xdg-utils package.


%prep
%setup -q -n 0d6eebb27c562e8644ccf616ebdbddf82d0d2dd8

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483036917
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdg-desktop-icon
/usr/bin/xdg-desktop-menu
/usr/bin/xdg-email
/usr/bin/xdg-icon-resource
/usr/bin/xdg-mime
/usr/bin/xdg-open
/usr/bin/xdg-screensaver
/usr/bin/xdg-settings

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
