#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-utils
Version  : 1.1.3
Release  : 24
URL      : https://portland.freedesktop.org/download/xdg-utils-1.1.3.tar.gz
Source0  : https://portland.freedesktop.org/download/xdg-utils-1.1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xdg-utils-bin = %{version}-%{release}
Requires: xdg-utils-license = %{version}-%{release}
Requires: xdg-utils-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : libxml2
BuildRequires : libxslt
BuildRequires : libxslt-bin
BuildRequires : links
BuildRequires : util-linux
BuildRequires : xmlto
BuildRequires : xset
Patch1: try-firefox.patch

%description
xdg-utils
---------
The xdg-utils package is a set of simple scripts that provide
basic desktop integration functions for any Free Desktop, such as Linux.

%package bin
Summary: bin components for the xdg-utils package.
Group: Binaries
Requires: xdg-utils-license = %{version}-%{release}

%description bin
bin components for the xdg-utils package.


%package license
Summary: license components for the xdg-utils package.
Group: Default

%description license
license components for the xdg-utils package.


%package man
Summary: man components for the xdg-utils package.
Group: Default

%description man
man components for the xdg-utils package.


%prep
%setup -q -n xdg-utils-1.1.3
cd %{_builddir}/xdg-utils-1.1.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604352671
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make test || :

%install
export SOURCE_DATE_EPOCH=1604352671
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-utils
cp %{_builddir}/xdg-utils-1.1.3/LICENSE %{buildroot}/usr/share/package-licenses/xdg-utils/c20e4d0f02dde640e3eae80839e4ccb2507b33a2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdg-desktop-icon
/usr/bin/xdg-desktop-menu
/usr/bin/xdg-email
/usr/bin/xdg-icon-resource
/usr/bin/xdg-mime
/usr/bin/xdg-open
/usr/bin/xdg-screensaver
/usr/bin/xdg-settings

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-utils/c20e4d0f02dde640e3eae80839e4ccb2507b33a2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xdg-desktop-icon.1
/usr/share/man/man1/xdg-desktop-menu.1
/usr/share/man/man1/xdg-email.1
/usr/share/man/man1/xdg-icon-resource.1
/usr/share/man/man1/xdg-mime.1
/usr/share/man/man1/xdg-open.1
/usr/share/man/man1/xdg-screensaver.1
/usr/share/man/man1/xdg-settings.1
